### PR TITLE
Initial commit of overview content.

### PR DESCRIPTION
**Pull request by stoobie**
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs-style-guide/1)

### CODE REVIEW

**Review by JameStark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs-style-guide/1)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @stoobie)

___
*[`components/StarkNet/modules/ROOT/pages/index.adoc` line 7 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs-style-guide/1#-NNq2V1m-OZ6z3fLEx27:-NNq2V1m-OZ6z3fLEx28:b-wa9tuy) ([raw file](https://github.com/starknet-io/starknet-docs-style-guide/blob/c781a6672a936cb4478dfb1975279fa49e62292d/components/StarkNet/modules/ROOT/pages/index.adoc#L7)):*
> ```AsciiDoc
> == About this guide
> 
> This guide provides style guidelines and preferred term usage for https://starknet.io/, including http://docs.starknet.io. Use it as a supplement to the following style guides:
> ```

starknet.io (don't think we need the https)



_Code quote:_
```AsciiDoc
https://starknet.io
```
___
*[`components/StarkNet/modules/ROOT/pages/index.adoc` line 7 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs-style-guide/1#-NNq2epe3GhKbyk1WnfC:-NNq2epe3GhKbyk1WnfD:b-szqp7y) ([raw file](https://github.com/starknet-io/starknet-docs-style-guide/blob/c781a6672a936cb4478dfb1975279fa49e62292d/components/StarkNet/modules/ROOT/pages/index.adoc#L7)):*
> ```AsciiDoc
> == About this guide
> 
> This guide provides style guidelines and preferred term usage for https://starknet.io/, including http://docs.starknet.io. Use it as a supplement to the following style guides:
> ```

docs.starknet.io (don't think we need the http)



_Code quote:_
```AsciiDoc
docs.starknet.io
```

**Review by JameStark — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs-style-guide/1)* status: all files reviewed, 2 unresolved discussions (waiting on @stoobie)

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs-style-guide/1)* status: all files reviewed, 2 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/ROOT/pages/index.adoc` line 7 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs-style-guide/1#-NNq2V1m-OZ6z3fLEx27:-NOOS5bs7H0jmazyjTs_:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs-style-guide/blob/c781a6672a936cb4478dfb1975279fa49e62292d/components/StarkNet/modules/ROOT/pages/index.adoc#L7)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

starknet.io (don't think we need the https)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/ROOT/pages/index.adoc` line 7 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs-style-guide/1#-NNq2epe3GhKbyk1WnfC:-NOOS5vi4FN8izpYHBXH:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs-style-guide/blob/c781a6672a936cb4478dfb1975279fa49e62292d/components/StarkNet/modules/ROOT/pages/index.adoc#L7)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

docs.starknet.io (don't think we need the http)
</blockquote></details>

Done.

**Review by JameStark — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs-style-guide/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stoobie)

**Review by JameStark — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs-style-guide/1#-:-NOOSsl92ZsAXJNdbxYj:bb6ywmx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stoobie)

**Review by JameStark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs-style-guide/1#-:-NOOSvWd7YPe8SOK5vFf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stoobie)

**Pull request merged**
